### ISSUE TITLE
Add property spying

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#101]
Allow SpyOn to be used for properties as well as functions

**Comment by Jameskmonger** [comment]
I think until we get this scoped into a milestone it would be good to at least throw a nice sensible error

**Comment by jamesrichford** [comment]
I figure that this is a useful feature and we've got so much in alpha.9 at the moment that we should sneak in another release in between :)

**Comment by jamesrichford** [comment]
Checklist

- [ ] expose getCalls and setCalls
- [ ] refactor spying to be super neat
- [ ] merge master back in (to get spy fixes)
- [ ] andSetValue
- [ ] andCallGetter
- [ ] andCallSetter
- [ ] restore
- [ ] add info to readme
