### ISSUE TITLE
Cannot find namespace 'NodeJS'

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#112]
With `1.0.0-alpha.8`, my project compiles fine.

With `1.0.0-alpha.9`, I get the following error:

    node_modules/alsatian/core/test-output.d.ts(4,28): error TS2503: Cannot find namespace 'NodeJS'.

**Comment by jamesrichford** [comment]
Looks like TestOutput is making reference to NodeJS as a global, looks like that's the problem!

**Comment by jamesrichford** [comment]
All fixed in alpha.11
