### ISSUE TITLE
Document Extending Expect 

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#126]
Thanks to lovely OO we can extend the Expect function so that people can create their own custom assertions e.g. `Expect(hexCode).isColor()`

Add some documentation as to how to do it.

**Comment by Jameskmonger** [comment]
I think it would be good to have it extendable directly, however this will mean that people have to then import their own `Expect` in an ugly way.

    import { Expect } from "alsatian";

vs

    import { MyExpect } from "../../../utils/expect-extension";

Not a complaint - just an observation and something to note in the docs.

**Comment by jamesrichford** [comment]
@Jameskmonger damn - forgot to assign myself to this! There are some functional changes that need to be made as well as documenting it - have you gotten anywhere with it?

**Comment by Jameskmonger** [comment]
Not got anywhere but I would like to pick it up if possible. I understand if you'd rather though, feel free to assign yourself.

**Comment by jamesrichford** [comment]
Well I can park what I've got in a PR the documentation isn't very exciting but can see what you think and maybe propose some differences? Can always close my PR if you start a fresh :)

**Comment by jamesrichford** [comment]
PS - sorry about the mix up @Jameskmonger but I'm sure you've definitely got some brain wave ideas :D
