### ISSUE TITLE
Split out spying into separate library

### ISSUE THREAD

**Issue by jamesadarich** [alsatian-test/alsatian#192]
If lyrebird needs spying which it probably will. Will want to have consistency between the two to minimise code duplication / big handling effort etc. Will need to confirm implementation as lyrebird progresses.

**Comment by Jameskmonger** [comment]
I'd say spying is probably part of the mocking anyway.

**Comment by jamesrichford** [comment]
This may need more thought and could result in an API change so moving to 2.0.0 for now

**Comment by jamesadarich** [comment]
Seems excessive so closing for now.
