### ISSUE TITLE
Rework namespacing

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#195]
Use indexes for nicer looking imports!

**Comment by Jameskmonger** [comment]
Indexes @jamesrichford ?

**Comment by jamesrichford** [comment]
@Jameskmonger https://www.typescriptlang.org/docs/handbook/module-resolution.html#how-typescript-resolves-modules

**Comment by jamesrichford** [comment]
Should consider people using module resolution classic when undertaking this task

**Comment by Jameskmonger** [comment]
Not sure what you mean @jamesrichford - it should be the same when compiled:

# Folder structure

    - index.ts
    - some_namespace/
    - - index.ts
    - - a.ts
    - - b.ts

# Source

## `index.ts`

    import { A, B } from "./some_namespace";

    let a = new A();
    a.getNumber(); // 3

    let b = new B();
    b.getLetter(); // "z"

## `some_namespace/index.ts`

    import { A } from "./a";
    import { B } from "./b";

    export { A, B };

## `some_namespace/a.ts`

    export class A {
        public getNumber(): number {
            return 3;
        }
    }

## `some_namespace/b.ts`

    export class B {
        public getLetter(): string {
            return "z";
        }
    }

---

Not sure how this can have any bad effect for any module resolution classic people?

**Comment by jamesrichford** [comment]
There may well not be anything wrong with it. It's just that because we're changing how things are imported (all be it slightly) we'll have to be mindful of those who are using a different compile option to make sure that it's OK for them.

Just a check really nothing more :)
