### ISSUE TITLE
Exported objects in test spec files causes error

### ISSUE THREAD

**Issue by ss108** [alsatian-test/alsatian#197]
I have a very large complex object I need as an arg for some functions I am testing. It's like 600 lines long, so naturally I put it in a separate file from my tests, a file named `mocks.ts` which is right alongside the file with my tests that use it. Because Alsatian tries to instantiate every exported member in the specified files/dirs as a test, I get an error, the relevant line of which is copied below.

I got around this by changing the contents of my `mocks.ts` to this:

```typescript
import { IgnoreTests } from "alsatian";

@IgnoreTests()
export default class Mocks {
    static get bigThing() {
        return _bigThing;
    }
}

const _bigThing = {
//my 600 line object

}

```

I think it's an easy enough work-around for the consumer of the lib, but isn't there a way to check if something has been annotated as a test by one of the relevant decorators before attempting to do whatever it is you do with `testFixtureConstructor`?

Thanks a bunch for writing this, by the way--I was very happy to discover it, and was real unhappy with my JS unit testing options previously, especially when TypeScript is in the mix.

```
TypeError: testFixtureConstructor is not a constructor
    at TestLoader._loadTestFixture 
```

**Comment by jamesrichford** [comment]
Hey Samier! Thanks for using Alsatian and your kind words! :)

I think I can see the problem here and looks quite easy to put a fix in so I'll have a look at this for you today :)

**Comment by jamesrichford** [comment]
Hey Samier,

To keep you updated I've created a PR which will go through our CI process and review process and aiming to get a new release (beta.2) out for you at approximately 13:00 UTC

**Comment by jamesrichford** [comment]
Hey Samier,

Should all be fixed now and published. Please update to beta.2 and let me know if this fits your needs. If there's still any issues or you have questions now or in the future please feel free to reopen this one or create a new issue.

Thanks,

James

**Comment by ss108** [comment]
@jamesrichford Thanks a bunch!! 

:beers:

**Comment by anodynos** [comment]
I just encountered the problem (with v2.3)  with an exported function (it was by mistake from a copy/paste) and I went crazy cause I was meddling with the test system in general and I had no clue what it was... 

Thank you google, github & you guys!

**Comment by jamesadarich** [comment]
Good spot there @anodynos looks like we've still got a problemo and we need to check whether the function we've picked is a constructor or not. I've opened an issue so we can resolve this and avoid future frustration 👍
