### ISSUE TITLE
Improve casting of spied function to FunctionSpy

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#220]
To extract calls or restore from code you need to cast a bit strangely so this could be improved

```
// Should be single cast
(<FunctionSpy><any>function).whatever
```

**Comment by jamesrichford** [comment]
I'm not sure this is going to be sensible really to make the types interchangeable. Perhaps the best thing is to update the documentation to be clearer. E.g.

```typescript
const spiedFunction = SpyOn(a, "function");

// access spy properties and functions
spiedFunction.calls;
spiedFunction.restore();
```

Any thoughts @Jameskmonger?

**Comment by Jameskmonger** [comment]
I haven't used the alsatian spying much yet - what exactly is the issue at the moment @jamesrichford?

**Comment by jamesrichford** [comment]
So the problem is that a `FunctionSpy` can be used itself as a function but TypeScript doesn't like that as it doesn't meet the type requirements. e.g.

```typescript

SpyOn(a, "function");

// the function is still a function but we've wrapped it in a spy
a.function();

// access to spy properties will be there at runtime but TypeScript doesn't allow at compile time
a.function.calls.length;
```

**Comment by jamesrichford** [comment]
Wiki updated :)
