### ISSUE TITLE
Errors on `npm install`

### ISSUE THREAD

**Issue by SiAdcock** [alsatian-test/alsatian#23]
<img width="794" alt="screen shot 2016-06-22 at 20 20 11" src="https://cloud.githubusercontent.com/assets/5931528/16280301/c5bec0de-38b6-11e6-8c75-cf971f76f17c.png">

😢

**Comment by jamesrichford** [comment]
Cheers Simon, looks like the test files are trying to be built on install - I'll fix immediately :)

**Comment by jamesrichford** [comment]
Thanks @SiAdcock - all fixed! :)
