### ISSUE TITLE
Ability to set timeout expiry on async tests

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#25]

**Comment by Jameskmonger** [comment]
Maybe `@AsyncTest(timeout)`? @jamesrichford

**Comment by jamesrichford** [comment]
Hey @Jameskmonger I was pondering this but you can use @AsyncTest to name tests as well as a short hand ```@AsyncTest("Name of test")```

I was thinking either as a second argument ```@AsyncTest("Name of test", 500)``` or another decorator ```@AsyncTestTimeout(500)``` or both - thoughts?

**Comment by Jameskmonger** [comment]
Can you do named parameters in TS like you would in C#? What's your opinion?

`@AsyncTest("Name of test", .timeout = 500)`

**Comment by jamesrichford** [comment]
Cool idea, but this is not possible in TypeScript.

However we could have overloads

@AsyncTest(description: string)
@AsyncTest(options: any)
@AsyncTest(descriptionOrOptions: any | string, options?: any)

**Comment by jamesrichford** [comment]
As discussed, the ```@AsyncTest``` decorator will not have a timeout argument but instead this will be a different decorator (see #56)

This will stay open however to be able to set the global timeout for all tests (default to no timeout)
