### ISSUE TITLE
how to debug in vscode

### ISSUE THREAD

**Issue by rlasjunies** [alsatian-test/alsatian#250]
hi,

 I like your work. 

 The only issue I've got for now is: how to debug *.spec.ts in vscode?

 I've done several trials without success playing in the launch.json file.

thank in advance

**Comment by jamesrichford** [comment]
Hi @rlasjunies

Thanks very much for your kind words I'm glad you're enjoying Alsatian. Unfortunately I'm away from my computer at the moment so I can't test it but I believe the below example should work in your launch.json. The program value will be the only one that may be different I've added an alternative if the initial one doesn't work. 

Let me know how you get on and I'll be glad to help with anything else! :)

Thanks, 

James

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug Unit Tests",
            "type": "node2",
            "request": "launch",
            "program": "${workspaceRoot}\\alsatian", // or "${workspaceRoot}\\node_modules\\alsatian\\cli\\alsatian-cli.js",
            "cwd": "${workspaceRoot}",
            "args": ["./**/*.spec.js"],
            "outFiles": [],
            "sourceMaps": true
        }
    ]
}
```

**Comment by rlasjunies** [comment]
hi @jamesrichford,

 Thank for your prompt reply.

 I passed thru this step before to ask you (looking in your unit test) , that's work. But we need to put the breakpoint in the transpiled *.spec.js files.

 The issue is that *.spec.js files generated are "ugly". TS, decorators, ... are polluating more and more the readability of the *.js files.

 As your concept is based on TS/class/decator, I would appreciate an "equivalent" experience for the debugging process, having breakpoint in the TS file.

 I've tried debugging "attaching" the debugger to alsatian ... but I am weak on this.

 It's not urgent, I can wait few days ;-)

Sincerely,

Richard

**Comment by jamesrichford** [comment]
Hey Richard, 

This is what the `sourceMaps` option should do in the launch.json

It may be in your TypeScript build that compiler options if missing the `"sourceMap": true,` option in your `compilerOptions` in your `tsconfig.json`

This should give you the ability to add breakpoints to the TypeScript directly. If you're still having trouble link me to the repo and I'll have a look :)

Thanks, 

James

**Comment by rlasjunies** [comment]
I've continued my tests. And you are right.

For the posterity here was "my mistake" / difference with your launch.json file. You have the value "node2" in the `type` where I've the value "node"

```
... good ...
 "type": "node2",
... > bad ...
"type": "node",
... < bad ...
```
Thank again!

**Comment by jamesrichford** [comment]
Excellent, have fun debugging! Should be great experience from what I've done in VSCode :)

Hope you continue enjoy using Alsatian!
