### ISSUE TITLE
run test through TestRunner result in no test to run

### ISSUE THREAD

**Issue by hong-duc** [alsatian-test/alsatian#252]
I have a simple `run-test.ts` like this
```
import { TestRunner, TestSet } from 'alsatian';
import tapSpec = require('tap-spec');
import path = require('path');

const testSet = TestSet.create();

testSet.addTestsFromFiles('dist/test/test1.spec.js');

const testRunner = new TestRunner();

testRunner.outputStream
    .pipe(tapSpec())
    .pipe(process.stdout);

testRunner.run(testSet);
```

and a simple test file `test1.spec.js` in the same folder 
```
import { Test, Expect } from 'alsatian';

export class Test1 {
    @Test('run test 1')
    public test() {
        Expect(1 + 1).toBe(2);
    }
}
```

if i run `alsatian dist/test/run-test.js` i will have error `no test to run`.
but if i run the file test directly `alsatian dist/test/test1.spec.js` it run the test normal
my alsatian version is `1.0.0`
What did i do wrong ?

**Comment by jamesrichford** [comment]
Hi @hong-duc,

If you're using the node API you should run the file in node directly.

In this case `node dist/test/run-test.js` :)

**Comment by hong-duc** [comment]
ohh i forgot about that,  i got used to the old way, thanks :smile:

**Comment by jamesrichford** [comment]
No problem :)
