### ISSUE TITLE
Look for AsyncSetup

### ISSUE THREAD

**Issue by ehallander9591** [alsatian-test/alsatian#286]
Is this feature ready to publish to npm? At least in the 1.0.1 version I have installed from npm I don't see the decorations for AsyncSetup.

Cheers

**Comment by jamesrichford** [comment]
Hi @ehallander9591,

Thanks for your interest. `AsyncSetup` has been prepped and is ready to go for release 1.1.0. I only have a couple of things to tidy up ready for this release so it should drop shortly. You can track the progress [here](https://github.com/alsatian-test/alsatian/milestone/26)

Thanks,

James

**Comment by jamesrichford** [comment]
Hi @ehallander9591,

1.1.0 is now available so this feature should be available.

Please let me know if you're having any trouble and I'll be glad to help. I've noticed one minor issue that you may or may not be affected by. If you are targeting es5 or below on your TypeScript build and not including a Promise shim or the es2015 typings libraries you may get a build issue like below:

```
node_modules/alsatian/core/decorators/async-test-decorator.d.ts(2,149): error TS2304: Cannot find name 'Promise'.
node_modules/alsatian/core/running/test-item.d.ts(10,27): error TS2304: Cannot find name 'Promise'.
node_modules/alsatian/core/running/test-runner.d.ts(9,46): error TS2304: Cannot find name 'Promise'.
```

If so simply add the es2015.promise lib or something containing it e.g. es2015.core

```
{
   "compilerOptions": {
      ...
      "lib": [ "es2015.promise" ],
      ...
   }
   ...
}
```
