### ISSUE TITLE
Investigate making types peerDependencies

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#303]
After browserifying alsatian we should investigate whether we make the types (@types/node etc.) peerDependencies - are they even required anymore? If not devDependencies

**Comment by Jameskmonger** [comment]
If the types are required for us to develop but nothing using those types is exported then they should be `devDependencies`. If they are required because we export them in some way then they should be `dependencies`.

Not sure the use of `peerDependencies`?
