### ISSUE TITLE
Test Structure example not working

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#319]
I'm looking at using Alsatian and I tried to follow the [Test Structure wiki entry](https://github.com/alsatian-test/alsatian/wiki/test-structure) but it didn't seem to work. The resulting output was:
```
$ ./node_modules/.bin/alsatian example.spec.js 
(node:6230) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token import
(node:6230) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I was expecting to see something like:
```
TAP version 13
1..1
ok 1 - exampleTest
```
[Here is a github repo](https://github.com/winksaville/test-alsatian1) of my test, what am I doing wrong?

**Comment by jamesrichford** [comment]
Hey @winksaville, I've just sent you a PR to fix the problem you're facing. Looks like you're trying to run Alsatian with TypeScript but the spec file you created `example.spec.js` alsatian is expecting to be able to run but it's actually the TypeScript source file.

I've done the following:
* added a `tsconfig.json` to define you're TypeScript settings
* added a pretest step to compile the TypeScript
* updated the `.gitignore' so the compiled files don't get committed

If you have any more questions please feel free to ask. Does this make sense and has it solved your issue?

**Comment by winksaville** [comment]
Thanks, may I suggest adding a little more information for noob's like myself at [Test Structure](https://github.com/alsatian-test/alsatian/wiki/test-structure) :)

**Comment by jamesrichford** [comment]
Sounds like a great idea, I'll add a simple TypeScript build into the wiki. Sounds good @winksaville?
