### ISSUE TITLE
Add Alsatian to wikipedia unit testing framework page

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#322]
I'd like to suggest Alsatian be added to [this](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#TypeScript) page.

**Comment by jamesrichford** [comment]
Sounds like a good idea to me @winksaville  👍

**Comment by winksaville** [comment]
Done, see the [new entry](https://en.wikipedia.org/wiki/List_of_unit_testing_frameworks#TypeScript). I'm closing this, but reopen if you'd like me to make other changes.
