### ISSUE TITLE
Alsatian doesn't appear to be terminating on Travis CI using Selenium and Chrome

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#332]
[Here](https://github.com/winksaville/nop-ts) is my project, it's using Selenium and Chrome for some tests. The test fixture that's hanging is [here](https://github.com/winksaville/nop-ts/blob/master/test/test-web.ts) and works fine on my local machine but [hangs on Travis CI](https://travis-ci.org/winksaville/nop-ts/builds/209465250).

Any suggestions on what the problem might be or how to debug it?

**Comment by jamesrichford** [comment]
Have you tried using spawn instead of exec. I seem to remember having an issue around this that had something to do with this in the past? If not I'd get the child process to log to the console too to see what was going on.

I'll continue to have a ponder about this though.

**Comment by winksaville** [comment]
Using spawn did it, [here](https://travis-ci.org/winksaville/nop-ts/builds/209567191) is the successful test.
And I changed starting the server using exec:
```
    this.server = child.exec('node build/server.js');
```
To using spawn:
```
    this.server = await child.spawn('node', ['build/server.js']);
```

TYVM!

**Comment by jamesrichford** [comment]
@winksaville great :) glad i could help
