### ISSUE TITLE
How to get test coverage of client side ts files

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#336]
I've created a minimal typescript based [web client/server app](https://github.com/winksaville/web-client-server-app-ts). I'm Alsatian and Selenium for testing, nyc/istanbul to get test coverage data and webpack to create a bundle.js file for the client code.

So here is the output from `nyc report` and there is no output for `client.ts`:
```
-----------------|----------|----------|----------|----------|----------------|
File             |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------------|----------|----------|----------|----------|----------------|
All files        |    94.95 |      100 |    83.33 |    94.38 |                |
 client          |    85.29 |      100 |    57.14 |    84.38 |                |
  client.spec.ts |    85.29 |      100 |    57.14 |    84.38 | 45,48,51,78,79 |
 common          |      100 |      100 |      100 |      100 |                |
  nop.spec.ts    |      100 |      100 |      100 |      100 |                |
  nop.ts         |      100 |      100 |      100 |      100 |                |
 server          |      100 |      100 |      100 |      100 |                |
  server.spec.ts |      100 |      100 |      100 |      100 |                |
  server.ts      |      100 |      100 |      100 |      100 |                |
-----------------|----------|----------|----------|----------|----------------|
```
Here is the code for `client.ts`:
```
$ cat src/client/client.ts
import * as m from "mithril";
import nop = require("../../dist/common/nop");

function invokeNop() {
  nop();
}

m.render(document.body,
  m("div", "Hello, click to ", [
    m("a", {href: "http://localhost:3000"}, "reload"),
    m("br"),
    m("button", {id: "invokeNop", onclick: invokeNop }, "invoke nop directly")
  ])
);
```
Here is how I'm creating `bundle.js` from `client.ts`:
```
    "_build:client": "tsc -p src/client/tsconfig.json && webpack dist/client/client.js dist/client/bundle.js",
```
Any suggestions how I might be able to get `client.ts` coverage ?

**Comment by jamesrichford** [comment]
@winksaville looks like it's saying `client.spec.ts` is missing coverage not `client.ts` so it should probably be as simple as excluding your spec files from the report :)

Incidentally the lines that aren't covered seem to be the debugging and error handling which I guess from a quick look should never be called as the tests are run normally

**Comment by winksaville** [comment]
The "client" line is for the directory not `client.ts`, notice that there are `server.ts` and `nop.ts` but no `client.ts`.  I tried adding includes but no `client.ts` or `client.js` or `bundle.js` for that manner . Do you have any repos where nyc was able to generate coverage information for client code?

**Comment by jamesrichford** [comment]
Ah @winksaville I think I understand what you mean.

The reason that `client.ts` is missing from nyc output is that it's never actually run. You'll need to `require("./client"):` in the spec file at the point you want to run the code inside it :)

**Comment by Jameskmonger** [comment]
@jamesrichford `import "./client.ts"; ` surely?

**Comment by jamesrichford** [comment]
@Jameskmonger the reason I went for `require` is that there are no exports from the file, therefore if performing multiple tests on it there may be a requirement to do different setup in the way of mocking, spies etc. for each test so you'd need to do this after the mocking is in place.

If you perform the `import` the code will be run beforehand and you can't import after other code has been run. :)

**Comment by winksaville** [comment]
I'm confused, your suggesting I need to require("client") in client.spec.ts but client.spec.ts is using selenium-webdriver to test client.ts. Below is the test that uses WebDriver to "press" the invokeNop button.
```
  @AsyncTest("wd: nop which is defined in a TS file")
  public async testWdNop() {
    debug("testWdNop:+");

    try {
      let button = await this.driver.findElement(By.id("invokeNop"));
      button.click();
    } catch (e) {
      debug(`testWdNop caught e=${e}`);
      Expect(false).toBe(true); // Always fail.
    }
    // Expect(false).toBe(true); // Always fail.

    debug("testWdNop:-");
  }
```
And as I mentioned in the original post `client.js` (created from `client.ts`) is bundled into bundle.js using webpack and then loaded from index.html:
```
$ cat public/index.html 
<!DOCTYPE html>
<html>
  <head> </head>
  <body>
    <script src='/build/bundle.js'>
    </script>
  </body>
</html>
```
Which is loaded when we "Get the home page" in setupFixture after starting the browser and server:
```
  @AsyncSetupFixture
  public async setupFixture() {
    debug("setupFixture:+");

    // Start the browser we're going to control
    this.driver = new Builder()
        .forBrowser(this.browserName)
        .build();

    // Start server
    this.server = await startServer(PORT, 5000, "./dist/server/server.js");

    // Get the home page
    await this.driver.get(`http:localhost:${PORT}/`);

    debug("setupFixture:-");
  }
```
I'm guessing I need something like [istanbul-instrumenter-loader](https://www.npmjs.com/package/istanbul-instrumenter-loader) but that looks to be for karma. [Here](https://github.com/zbicin/angular-webpack-typescript-karma-coverage) is another example using it.

Hopefully you guy can point in the right direction.

**Comment by jamesrichford** [comment]
@winksaville I think there has been a little confusion here.

To summarise:

* `client.ts` needs to be covered
* nyc is showing gaps in coverage at lines 45,48,51,78,79
* `client.ts` does not have 45 lines so it cannot be missing coverage here
* `client.spec.ts` however does have enough lines and the lines in that file matching to those numbers are debugging lines which I suspect aren't called in scope of the test
* `client.spec.ts` not being excluded from the report is probably the cause

This info on [excluding files in nyc](https://github.com/istanbuljs/nyc#excluding-files) should help I hope :)

**Comment by winksaville** [comment]
@jamesrichford the lines 45,48,51,78,79 are for client.spec.ts:
```
  client.spec.ts |    85.29 |      100 |    57.14 |    84.38 | 45,48,51,78,79 |
```
And those lines aren't being executed and there is no reason to really include *.spec.ts files. But thought it might be helpful to not exclude or include anything to diagnose the problem. Anyway, yesterday I added a "nyc" section below:
```
  "nyc": {
    "include": [
      "dist"
    ]
  }
```
And the dist directory contains:
```
$ tree dist
dist
├── client
│   ├── bundle.js
│   ├── client.d.ts
│   ├── client.js
│   └── client.js.map
├── common
│   ├── delay.d.ts
│   ├── delay.js
│   ├── delay.js.map
│   ├── nop.d.ts
│   ├── nop.js
│   └── nop.js.map
└── server
    ├── server.d.ts
    ├── server.js
    └── server.js.map
```
And now the report is as follows:
```
------------|----------|----------|----------|----------|----------------|
File        |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
------------|----------|----------|----------|----------|----------------|
All files   |      100 |      100 |      100 |      100 |                |
 common     |      100 |      100 |      100 |      100 |                |
  delay.ts  |      100 |      100 |      100 |      100 |                |
  nop.ts    |      100 |      100 |      100 |      100 |                |
 server     |      100 |      100 |      100 |      100 |                |
  server.ts |      100 |      100 |      100 |      100 |                |
------------|----------|----------|----------|----------|----------------|
```
As you can see there is no `client` info at all using the include.

I did some more digging and [tests](https://github.com/winksaville/web-client-server-app-ts/commit/db23d9b7aeb709d2ccfd7e73d420a8de7b05b2d9) and have now [concluded](https://github.com/winksaville/web-client-server-app-ts/issues/1), maybe incorrectly, that istanbul needs additional support to be able to capture coverage Information from code running in a browser. One
solution appears to be [istanbul-middleware](https://github.com/gotwarlost/istanbul-middleware) but that is apparently no longer [actively supported](https://github.com/istanbuljs/nyc/issues/519).

Anyway, I hope I'm wrong and that maybe you have an example where it does work!

**Comment by jamesrichford** [comment]
@winksaville yes, I would imagine that this is the case that nyc (or istanbul) won't support this use case.

I would say the reason for this is that Selenium should be used for end to end testing generally, so how a user will interact with the app. For this use case code coverage doesn't tell us a great deal.

For your unit testing however, I'd recommend running all tests on the server side regardless of where the production code will be run. Benefits of this include:

1. No assumptions - you're not making any environment based assumptions in writing your code so it is portable can be run on client, server or wherever there is a JS engine. This also gives you the ability to render client side code on both the server and the client which can be super useful if you need to get HTML to the user fast.
2. Speed - running up a web server, a browser and all the other stuff that goes along with client side testing takes time and for larger apps you could easily have thousands of tests (if not more) and this will impact CI builds and development.
3. Simplicity - less to go wrong, running up all these different solutions gives you so many points of possible failure and along with that the frustration and extra time given diagnosing and fixing such issues. Keep it simple Alsatian + node :)
4. Development environment - usually you have to make some assumptions for example that a specific browser is installed when running these sorts of test (and yes you can choose Chrome and it would be a pretty good assumption) but if you want to work as a team you have to ensure your solution can be developed anywhere, different setups, OSes, preferences. To get the best out of developers let them work in the environment that suits them.
5. TDD - running unit tests in this way enables TDD to be performed, waiting for browsers to spin up etc. really break the flow and can stutter your development experience.

**Comment by winksaville** [comment]
Thanks for the tips, I don't completely concur as the code on the client side is not the same environment as that of the server. So I'd like to try to do thorough testing on both sides. For now, since client side code coverage isn't practical, I'll do testing on both but only get code coverage numbers on the server side.

And, as you suggest, I absolutely want as much of my code to work isomorphically as possible and all of that isomorphic code will get code coverage data so I think things will be fine for now.

Thanks again!
