### ISSUE TITLE
Test fixture does not have to be a class

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#341]
The test fixture does not have to be a new-able class. It can currently just be a function without any class behaviour.

The `@TestFixture` decorator takes an argument `constructor: Function`. I think that this type could be improved to be `contructor: { new(...args: Array<any>): any; }`, therefore enforcing that `@TestFixture` is called on a class rather than an object (which seems to be the requirement from the docs)

**Comment by jamesrichford** [comment]
@Jameskmonger I don't think it will be allowed to be used as a decorator in this way but I think it's a good change to be done anyway 👍

**Comment by jamesrichford** [comment]
closed by #390
