### ISSUE TITLE
How to pass parameters to node js

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#345]
I like to pass parameters to node js when executing alsatian. For example I want to pass the "--expose-wasm" parameter to node js, how do I do this?

**Comment by winksaville** [comment]
I've got a solution:
```
node --expose-wasm node_modules/.bin/alsatian <file to run>
```
Is there a better one?

**Comment by jamesrichford** [comment]
Hey @winksaville,

What is the purpose of passing parameters - is it to test that those parameters affect your code under test?

**Comment by winksaville** [comment]
I'm writing some WebAssembly tests and thus I must pass --expose_wasm to
node so the functionality is available.

**Comment by jamesrichford** [comment]
I'd say setting the `process.argv` array will probably be the easiest way to achieve this as it'll be easy to change it :)

**Comment by winksaville** [comment]
I can't do that from the outside, can I? One thought would be if node parameters were present it would relanuch itself with the node parameters otherwise continue. One possible way to identify node parameters is to require them to come before alsatian parameters and separate them with a "--":

So if there were no node parameters than execution would identical:
```
$ alsatian file.js --tap
```
And if node parameters were needed:
```
$ alsatian --expose_wasm -- file.js --tap
```
Other schemes are possible, just a suggestion.

**Comment by winksaville** [comment]
The solution of executing Alsatian seems a passable solution for now, so closing. Reopen or comment if better solutions become known.

**Comment by jamesrichford** [comment]
Thanks @winksaville just to clarify I think that passing arguments alsatian directly for your code probably doesn't quite make sense. Either passing them to the code before running Alsatian if you were starting up a service that you wanted to test or passing the arguments from inside your Alsatian tests are the best approaches.

Was there a particular reason you were looking to pass arguments in this way?

**Comment by winksaville** [comment]
Look at the first post, this wasn't to pass parameters to my alsatian code, this was to pass parameters to nodejs. In particular I needed to pass ```--expose_wasm``` to nodejs. Although being able to pass command line parameters to my alsatian code would be a very good feature, but that isn't what I was asking for.

**Comment by jamesrichford** [comment]
I'd say that this is totally possible inside alsatian but maybe a mini library simplifying the process would make life easier.

To clarify how to do this using (https://nodejs.org/api/child_process.html)[node child process] is probably the way forward :)

Here's a simple modified snippet taken from Alsatian's own tests to display examples of testing you can do.

```typescript
import * as child from "child_process";
import * as path from "path";
import { AsyncTest, Expect, TestCase, TestFixture, Timeout } from "alsatian";

@TestFixture("TypeScript compiler tests")
export class TypeScriptCompilerTests {

   @TestCase("es3")
   @TestCase("es5")
   @TestCase("es6")
   @TestCase("es2015")
   @AsyncTest("Compiler supports all targets")
   @Timeout(5000)
   public targetBuildCompiles(target: string) {

      const result = child.exec("tsc -p ./test/integration-tests/typescript --target " + target);

      let consoleOutput = "";
      let consoleErrorOutput = "";

      result.stdout.on("data", (data) => consoleOutput += data);        // record console logging for testing later
      result.stderr.on("data", (data) => consoleErrorOutput += data); // record console error logging for testing later

      return new Promise<void>((resolve, reject) => {
         result.on("close", (code: number) => {
            Expect(code).toBe(0); // determine whether the process was successful (0 = yes)
            resolve();
         });
      });
   }
}
```
