### ISSUE TITLE
Unhandled promise rejection when mocking 

### ISSUE THREAD

**Issue by ginomarckx** [alsatian-test/alsatian#355]
I am relatively new to the whole JS/TS ecosystem and Alsatian makes more sense to me than Jasmine does (especially for mocking capabilities), so I'm excited to get it to work.

The error I'm getting on a simple run in the following.
```
(node:25041) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): SyntaxError: Unexpected token import
(node:25041) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The test I am executing:
```
import { Expect, Test } from 'alsatian';

export class TestFixture {
  @Test('to see if this works')
  public test() {
    Expect(1 + 1).toBe(2);
  }
}
```

My setup is based on the latest angular CLI setup, so tests are stored alongside the code and there are 2 tsconfig.json (app and spec) files both extending the same parent. I am not even sure which information to provide for anyone to help me out ;)

*tsconfig.json*
```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

*tsconfig.spec.json*
```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/spec",
    "module": "commonjs",
    "target": "es5",
    "baseUrl": "",
    "types": [
      "jasmine",
      "node"
    ]
  },
  "files": [
    "test.ts"
  ],
  "include": [
    "**/*.spec.ts",
    "**/*.d.ts"
  ]
}
```

I added the following line to my scripts in package.json to try it out.
```
    "tst": "alsatian \"src/main/angular/**/*.alspec.ts\"",
```

Is there anyone who can help me getting rid of the errors above (and Jasmine)?

**Comment by jamesrichford** [comment]
Hi @ginomarckx,

Thanks for checking out Alsatian! Your error looks quite strange and doesn't seem to match up with the code you've got.

Could you send me a link to your repo please?

Thanks,

James

**Comment by ginomarckx** [comment]
In what I attached, I left in only 1 Jasmine test and 1 Alsatian test.
In stripping everything out, I noticed that the config file .angular-cli.json was used. 

Thanks already for your help!

[test-alsatian.zip](https://github.com/alsatian-test/alsatian/files/920487/test-alsatian.zip)

**Comment by jamesrichford** [comment]
I've just noticed the issue.

Your test command is pointing to the typescript files and not the compiled javascript

Change:

```
"tst": "alsatian \"src/main/angular/**/*.alspec.ts\"",
```
to

```
"tst": "alsatian \"src/main/angular/**/*.alspec.js\"",
```

You'll also need the typescript to be compiled before running the tests :)

We could do with updating alsatian to improve the error message coming from this though.

**Comment by jamesrichford** [comment]
@ginomarckx just created an issue to add more info to help debugging. Let me know if the above resolves your issue :)
