### ISSUE TITLE
Create Expect.fail

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#359]
Most other test frameworks have a `fail` function.

This would have made @winksaville 's initial workaround in #353 much cleaner as he could have done:

```
try {
    await this.asyncThrowError(delayMs);
    Expect.fail("No error thrown");
} catch(err) {
    Expect(err).toBeTruthy();
}
```

**Comment by winksaville** [comment]
Please add fail :)

**Comment by jamesrichford** [comment]
Sounds simple enough.

Accepted
