### ISSUE TITLE
Rename FocusTests/IgnoreTests to ___TestFixture

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#363]
I think `FocusTestFixture` would be more natural than `FocusTests`

**Comment by jamesrichford** [comment]
Looks good to me. We'll need to add a deprecation notice in 1.x versions though :)

**Comment by Jameskmonger** [comment]
@jamesrichford would it be possible to simply have `@Focus` and `@Ignore` which can be applied to both test fixtures and tests?

**Comment by jamesrichford** [comment]
Sorry, dunno how I missed this @Jameskmonger yes, I think that should work just need to merge the two decorators :)

**Comment by jamesadarich** [comment]
There is now a common `Focus` and `Ignore` decorator so no longer an issue
