### ISSUE TITLE
Unable to call spy function

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#380]
```typescript
import { FunctionSpy } from "alsatian";

const spy = new FunctionSpy();

spy(); // TypeError: spy is not a function
```

**Comment by jamesrichford** [comment]
I'm sure we discussed this before @Jameskmonger but can't find the conversation. I think what we need to do is replace this with a `createFunctionSpy` function that does the following.

```typescript
function createFunctionSpy() {
      const functionSpy = new FunctionSpy();

      const spiedFunction = functionSpy.bind(this);

      // expose spy's calls on function
      spiedFunction.calls = functionSpy.calls;

      // expose spy's callsWithArguments on function
      spiedFunction.callsWithArguments = functionSpy.callsWithArguments;
}
```

This has been extracted from `RestorableFunctionSpy` so gives us an opportunity to refactor.

**Comment by Jameskmonger** [comment]
I think we may also want to update the docs as they made me believe I could just use a `new FunctionSpy`

https://github.com/alsatian-test/alsatian/wiki/spying#creating-a-spy-from-thin-air
