### ISSUE TITLE
Use stricter tsc compiler options

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#383]
Currently the only "strict" compiler option I see is:
```
    "noImplicitAny": true,
```
I use the following in my projects:
```
    "noImplicitAny": true,
    "alwaysStrict": true,
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noEmitOnError": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
```
I was wondering if team would accept PR's that attempted to use stricter options?

Currently when I try to compile with the values above I see mostly "declared but never used" errors, which might be "easily" fixed:
```
$ tsc 
cli/alsatian-cli-options.ts(13,4): error TS2322: Type 'null' is not assignable to type 'number'.
cli/alsatian-cli-options.ts(82,30): error TS6133: 'value' is declared but never used.
cli/alsatian-cli-options.ts(97,27): error TS6133: 'value' is declared but never used.
cli/alsatian-cli-options.ts(109,30): error TS6133: 'value' is declared but never used.
cli/alsatian-cli-options.ts(124,30): error TS6133: 'value' is declared but never used.
cli/alsatian-cli-options.ts(139,27): error TS6133: 'value' is declared but never used.
cli/alsatian-cli-options.ts(148,53): error TS6133: 'index' is declared but never used.
cli/alsatian-cli-options.ts(167,10): error TS2322: Type 'null' is not assignable to type 'string'.
core/decorators/async-setup-decorator.ts(7,28): error TS6133: 'descriptor' is declared but never used.
core/decorators/async-setup-fixture-decorator.ts(7,35): error TS6133: 'descriptor' is declared but never used.
core/decorators/async-teardown-decorator.ts(7,31): error TS6133: 'descriptor' is declared but never used.
core/decorators/async-teardown-fixture-decorator.ts(7,38): error TS6133: 'descriptor' is declared but never used.
core/decorators/async-test-decorator.ts(8,12): error TS6133: 'descriptor' is declared but never used.
core/decorators/focus-test-decorator.ts(4,64): error TS6133: 'descriptor' is declared but never used.

**Comment by jamesrichford** [comment]
The only mild reservation I have is decorator functions have a given signature and it'd be nice to show people the parameters they can use when extending the decorator functionality as some developers unfamiliar with them may miss the opportunity. But it's quite niche perhaps?

**Comment by jamesrichford** [comment]
Any thoughts @Jameskmonger?

**Comment by Jameskmonger** [comment]
What do you mean by your point re decorator signatures?

**Comment by jamesrichford** [comment]
Sometimes we don't use the descriptor argument but it's always passed in to the decorator so should we keep the argument in this case because it's passed in so better reflects the actual signature rather than the arguments we use.

**Comment by winksaville** [comment]
I'll work up a straw man PR and see what people think.

**Comment by jamesrichford** [comment]
Sounds like a plan :)

**Comment by jamesrichford** [comment]
Still work to do before all flags in place @winksaville has kindly documented the current list remaining which is mainly specs

https://gist.github.com/winksaville/1e0ef24ad21fe534d452d5a0684635c7
