### ISSUE TITLE
Not all test cases appear in output

### ISSUE THREAD

**Issue by gwalschl** [alsatian-test/alsatian#387]
Hello,
If I define multiple @TestCase statements above a test, it seems that when running the tests they all run, but not all @TestCase statement appears in the console output.  I'm running Alsatian from npm test within terminal of Visual Studio Code and have attached screenshot.
Thanks!
![image](https://cloud.githubusercontent.com/assets/12500736/25895976/80b74098-353f-11e7-88d4-293f56558063.png)

**Comment by Jameskmonger** [comment]
Hi @gwalschl, thanks for reporting this.

The way it works at present is you should only see one test case at a time - however there is a bit of an issue which is causing it to drag across multiple lines.

Currently, we have developed this ourselves. However we have put a pull request in to [the log-update package](https://github.com/sindresorhus/log-update/pull/21) and will be using that which will fix this issue.

Thank you for your patience!

**Comment by gwalschl** [comment]
Thanks!  I do like your work and the package is nice.
