### ISSUE TITLE
Please do a new release of Alsatian

### ISSUE THREAD

**Issue by winksaville** [alsatian-test/alsatian#395]
I'm using toThrowAsync and I'd sure like you to do a new release so I don't have to use master. Especially since I have to build it locally since I can't use it as is, I believe this is issue #364 and #365.

**Comment by jamesrichford** [comment]
Hey @winksaville,

I'm just finishing off some pieces for #359 and #373 which will hopefully be super useful for you but have been a bit slower as there is a breaking change in extending `Expect` that I just wanted to minimize the impact for. Also note that this means Alsatian will be moving to 2.0.0 on the next release :). I can move the rest of the stuff outstanding to the next release to push this one quicker if that would be an acceptable compromise?

Also I'm planning on creating a `next` tag npm release nightly when there are changes so you can get the next release early if preferable #375 I can up the priority of this one too if you think this would also be useful? :)

**Comment by winksaville** [comment]
Being selfish, I'd like to see what you've got released without any breaking changes, but it's your baby :)

A `next` tag would be great if it can be used directly using something like `yarn add -D https://github.com/alsatian-test/alsatian.git/nightly`. Actually, I suggest adding `release candidate` tag which is "guaranteed" to be "functional" (i.e. passes all tests) as I suspect nightly's could be broken.

**Comment by jamesrichford** [comment]
@winksaville to be clear the only breaking change is in the extending expect functionality

https://github.com/alsatian-test/alsatian/wiki/extending-expect

Are you using this? If not then there will be no breaking changes for you :)

The nightly design is going to be a very strong nightly, it must pass all tests and checks and will only contain those that have gone through the full process and merged back to master. Anything else will be exempt from the nightly so no worries there. The goal of that is to resolve the situation where we have new features to go but waiting on others being merged etc. Sound like it'll be fit for purpose?

**Comment by winksaville** [comment]
Not extending Expect, so no problem there.

And yep, that nightly design is just fine. I assume there will be a
"permanent" tag maybe based on "date/time" as there are times when I just
want the "latest" and times I want to stay on a particular Nightly for a
while and then move in weekly or some other step.

Will the nightly be "installable" directly with `npm`/`yarn`?

**Comment by jamesrichford** [comment]
@winksaville the design will be to have two tags `latest` and `next`

`latest` will provide the latest non-nightly release (i.e. certified stable)

`next` will provide the latest nightly release (i.e. latest tested code in master)

Both will be available via npm / yarn via `npm install alsatian@latest` and `npm install alsatian@next` (same for yarn but replace the command :) )

The release number for the nightly releases will be the upcoming stable release number plus the date stamp for that night (UTC) e.g. (2.0.0-20170525)

**Comment by winksaville** [comment]
SG, txs!

**Comment by jamesrichford** [comment]
Hi @winksaville just a tiny bit more to do on 2.0.0 most of the PRs are in. I've created a manual nightly build for you though so you can test out the above. `npm install alsatian@next` should get you the current stable prerelease version of alsatian 2.0.0 :)

**Comment by winksaville** [comment]
Will test it later today, I'm traveling right now.

**Comment by winksaville** [comment]
Sorry, been busy on my little vacation to San Diego for a wedding. Just tried alsatian@next in my [test-Alsatian-Expect-toThrow-async](https://github.com/winksaville/test-Alsatian-Expect-toThrow-async/commit/6ad8b2d0a59bf9641eae23ebffe071020cfc4428), worked like a charm.

**Comment by winksaville** [comment]
@jamesrichford, I'd still like a solution to "How to easily use a personal Alsatian branch #364".

**Comment by jamesrichford** [comment]
No problemo @winksaville by all means! I hope you enjoyed / are continuing to enjoy it.

#364 as well as getting the auto nightly releases will be a priority for me coming through as it'll add a big benefit allowing people to check out new features as soon as possible but also we can be more confident about upcoming releases too! :)

**Comment by winksaville** [comment]
TXS

**Comment by jamesrichford** [comment]
Hey @winksaville I'm gonna close this one now as Alsatian 2.0.0 has been released :)

**Comment by winksaville** [comment]
Nice!
