### ISSUE TITLE
Add documentation on expected failure output

### ISSUE THREAD

**Issue by markamccann** [alsatian-test/alsatian#416]
I've written simple test that I expect to fail:
```
import { Expect, Test, TestCase, TestFixture } from "alsatian";

@TestFixture()
export class DebugAlsatianFixture {

  @TestCase(1, 2)
  simpleEqualityFailTest(a: number, b: number) {
    Expect(a).toBe(b);
  }
}
```

Should I be expecting a slightly more helpful error message other than what I'm getting?

```
DebugAlsatianFixture
simpleEqualityFailTest ( 1, 2 )
|====================|

Pass: 0/1
Fail: 1/1
Ignore: 0/1

FAIL: simpleEqualityFailTest ( 1, 2 )
The test threw an unhandled error.
Expected: no unhandled errors to be thrown
  Actual: an unhandled error
```

Looking at some of this project's test cases makes me think the above isn't correct.  BTW, it does pass for correct tests, but failures are always indicated by an "unhandled error" message.  I'm on Alsatian 2.0.0.

**Comment by Jameskmonger** [comment]
This isn't correct behaviour - thank you for reporting it!

You should get something like this:

```
FAIL: simpleEqualityFailTest ( 1, 2 )
Expected: 2
  Actual: 1
```

**Comment by markamccann** [comment]
Thanks for replying James.  I'm getting similar behavior for any failing test.  Is this because my node environment is too bleeding edge.  Node 8.4.0, npm 5.3.0, TypeScript 2.5.2?  In my tsconfig.json, I have "compilerOptions": { "target": "es2017", "lib": [ "es2017", "dom" ] ...

**Comment by markamccann** [comment]
I'm not exactly sure why, but the problem seemed to be a difference between my global install of alsatian and my local install for the project.  When I changed my test to use `./node_modules/.bin/alsatian`, tests fail as per normal.  Thanks for the help.
