### ISSUE TITLE
Typescript tests

### ISSUE THREAD

**Issue by 11000100111000** [alsatian-test/alsatian#419]
Is there a way to run the tests in typescript directly without needing to transpile every testfile?

**Comment by jamesrichford** [comment]
@11000100111000 interesting question, is it that you want to have something where you save one file and it only runs the tests in that file?

**Comment by brad-jones** [comment]
I think @11000100111000 is referring to the ability to use something like https://github.com/TypeStrong/ts-node to run tests without having to first compile the test to js yourself. At least that is what I came to this issue to find out how to do.

**Comment by jamesrichford** [comment]
Yeah, I would imagine this would work - I can't see a reason it wouldn't. Have you given this a go @brad-jones

**Comment by brad-jones** [comment]
Yes it does work if you create your own runner script. And then execute the runner with ts-node.
ie: `ts-node ./tests/runner.ts`

```ts
import { TapBark } from "tap-bark";
import { TestSet, TestRunner } from "alsatian";

(async () =>
{
    const testSet = TestSet.create();
    testSet.addTestsFromFiles('./**/*.spec.ts');

    const testRunner = new TestRunner();

    testRunner.outputStream
        .pipe(TapBark.create().getPipeable())
        .pipe(process.stdout);

    await testRunner.run(testSet);
})().catch(e =>
{
    console.error(e);
    process.exit(1);
});
```

I think the expectation is that because this is a typescript test framework that out of the box the `alsatian` command would have compiled typescript on the fly for you, at least that is what I thought it was going to do.

While it might seem blatantly obvious to the developers of alsatian I think the wiki page (https://github.com/alsatian-test/alsatian/wiki/typescript-setup) needs an extra sentence reminding you that you are responsible for compiling the tests to js. 

Anyway I'm happy with my setup now.

**Comment by jamesrichford** [comment]
Added some tests in the above PR to ensure this works with further updates :)

Thanks @brad-jones for checking this out I will add this to the wiki then close 👍

**Comment by anodynos** [comment]
I think it doesn't work anymore - I get 

```
ERROR LOADING FILE: ../fo.spec.ts
.../foo.spec.ts:1
(function (exports, require, module, __filename, __dirname) { import * as _ from 'lodash';
                                                                    ^

SyntaxError: Unexpected token *
    at new Script (vm.js:84:7)
    at createScript (vm.js:264:10)
    at Object.runInThisContext (vm.js:312:10)
    at Module._compile (internal/modules/cjs/loader.js:696:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:747:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/anodynos/.npm/_npx/25517/lib/node_modules/ts-node/src/index.ts:406:14)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:568:12)
    at Function.Module._load (internal/modules/cjs/loader.js:560:3)
    at Module.require (internal/modules/cjs/loader.js:665:17)npm ERR! code ELIFECYCLE
```
    "test-runner": "ts-node -r ts-node/register src/test/alsatianTestRunner.ts",
    "test-runner2": "npx -p ts-node -p typescript ts-node src/test/alsatianTestRunner.ts",

with both ts-node@7 & ts-node@8 (using alsatian@2.3.0) 

Mentioning #434 that tracks this issue.
