### ISSUE TITLE
Any doesn't accept a missing argument

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#423]
const obj = {
        foo: (a: any, b: any) => { }
    };

    SpyOn(obj, "foo");

    foo(10, 20);

    Expect(obj.foo).toHaveBeenCalledWith(10, 20, Any);

I would expect the above test to pass (i.e. `Any` to accept a missing argument) but instead it fails

**Comment by jamesrichford** [comment]
@Jameskmonger this is expected behaviour as you are saying it should have been called with 3 arguments but it was called with 2.

Have you got a use case this is relevant for?

**Comment by jamesrichford** [comment]
@Jameskmonger bump

**Comment by Jameskmonger** [comment]
I don't have a use case for it at present. However given the nature of JavaScript I would expect to be able to  ignore an argument in an assertion.

**Comment by jamesrichford** [comment]
I'd say if you can't be sure whether a function will be called with 2 or 3 arguments in a given test probably highlights a problem with the code or the test, wouldn't you say @Jameskmonger?

**Comment by Jameskmonger** [comment]
Yes @jamesrichford I agree but I know some people that might disagree :laugh:

**Comment by jamesrichford** [comment]
Closing as not required. Please reopen if anything changes :)
