### ISSUE TITLE
Add Coverage as stated in the wiki

### ISSUE THREAD

**Issue by jhm-ciberman** [alsatian-test/alsatian#437]
Hello. I am trying to add coverage report like stated in the wiki. But I got this output:

```
> docs_gm@1.0.1 coverage F:\repos\public\docs_gm
> npm run build && nyc --reporter=lcov --reporter=html npm run unit-tests && nyc report


> docs_gm@1.0.1 build F:\repos\public\docs_gm
> tsc -p .


> docs_gm@1.0.1 unit-tests F:\repos\public\docs_gm
> alsatian ./dist/**/*.spec.js
GMS2Resource
should throw when calling subScripts() without calling loadFromString
|====================|

Pass: 50/50
Fail: 0/50
Ignore: 0/50
----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
```

This is my package.json:

```
  "scripts": {
    "pretest": "npm run lint",
    "test": "npm run test-only",
    "pretest-only": "npm run build",
    "test-only": "npm run unit-tests",
    "unit-tests": "alsatian ./dist/**/*.spec.js",
    "build": "tsc -p .",
    "watch": "tsc -p . --watch",
    "clean": "rimraf ./dist/",
    "testing": "alsatian ./dist/**/*.spec.js",
    "coverage": "npm run build && nyc --reporter=lcov --reporter=html npm run unit-tests && nyc report",
    "lint": "tslint --project . -t verbose",
    "prepublishOnly": "npm run clean && npm run build"
  }
```

This is my tsconfig.json:
```json
{
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ],
  "compileOnSave": true,
  "compilerOptions": {
    "noEmitOnError": true,
    "target": "es2016",
    "module": "commonjs",
    "declaration": true,
    "inlineSourceMap": true,
    "outDir": "./dist/",
    "rootDir": "./src/",
    "strict": true,

    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,

    "experimentalDecorators": true
  }
}
```

**Comment by jhm-ciberman** [comment]
I fixed it. The problem was that I was using `inlineSourceMap` instaed of `sourceMaps` in my `tsconfig.json`.

It would be great if this requirement is documented on the wiki.

**Comment by jamesrichford** [comment]
Interesting @jhm-ciberman what was the reason for using online source maps? Might have a little look into this as seems strange it shouldn't work so worth figuring out why :) but yes if there is a major incompatibility we'll pop it on the wiki - good find!!

**Comment by jhm-ciberman** [comment]
No reason at all. I migrated from Jest to Alsatian, so the `inlineSourceMaps` option just got left there. I used inlineSourceMaps as it polutes less the `./dist/` directory.

**Comment by jhm-ciberman** [comment]
Hello again. Can this be closed? 

Also, I got some time free now, do you need help with some specific issue?

**Comment by jamesrichford** [comment]
I just wanted to check out inline source maps briefly before closing :)

**Comment by vnen** [comment]
I get something like this too, but it's not related to inline source maps. When I run the test via Gulp, the coverage is unknown. If I use the `alsatian` command directly (like in the wiki example) then the coverage is reported correctly, even with inline source maps.

This is a bit cumbersome because the TypeScript files need to be transpiled first, but I can work around by calling `gulp build` in the npm script line.

**Comment by jamesadarich** [comment]
I think this should now be resolved as you can pass typescript files directly to alsatian. Please reopen or as new issue if you're facing issues :)
