### ISSUE TITLE
Fix linting issues (specially, indentation)

### ISSUE THREAD

**Issue by jhm-ciberman** [alsatian-test/alsatian#438]
Hello. I have forked the repo and I want to contribute, but I have tried running `npm run fix-linting-issues` but the number of linting issues is huge. 
Can you please lint the whole project whit a consistent formating? 
For example, some files use 3 spaces indentation, other uses 2, other 4, and others mix between 2,3 and 4. 

Also, please add the following to the `.vscode/settings.json` file to exclude from the file explorer all the generated files:

```json
    "files.exclude": {
        "**/.git": true,
        "**/*.js": true,
        "**/*.d.ts": true,
        "**/*.js.map": true,
        "coverage": true,
        ".nyc_output": true,
    }
```

If you use visual studio code, I recomend you to install the [TSLint extension](https://github.com/Microsoft/vscode-tslint.git) for VScode to be able to view linting on the same file.

**Comment by jamesrichford** [comment]
Strange that we've got this but worth adding a rule to the tslint.json if it's not resolving at the moment :)

**Comment by jhm-ciberman** [comment]
I would love to contribute. If you fix this I can contribute with all the other issues.

**Comment by jamesrichford** [comment]
Awesome I'd definitely appreciate the help. I'll see what I can do asap :)

**Comment by jhm-ciberman** [comment]
I will be waiting. Please let me updated.
