### ISSUE TITLE
setTimeout not called in asyncTest

### ISSUE THREAD

**Issue by wip0** [alsatian-test/alsatian#447]
![2018-02-02_18h11_50](https://user-images.githubusercontent.com/20312631/35729967-fa438490-0842-11e8-94c9-c2417a6efb9f.png)

Code at Line 15 has never been called regardless of any timeout value. And then the test failed.

I use alsatian version 2.1.0, typescript 2.6.2

**Comment by jamesrichford** [comment]
Hey @wip0,

I've tried to reproduce this but didn't manage it. Any chance of checking out the repo?

Or what failure message did you get? A timeout?

With regards to the timeout there is a neater way of writing it which I generally use but could be worth adding to alsatian

```typescript
async function wait(timeout: number) {
    return new Promise(resolve => setTimeout(resolve, timeout);
}
```

Means you could rewrite the above to

```typescript
@TestCase('Ch:1', '12345')
@AsyncTest('Callback is called')
public async callbackTest(ch1: string, msg1: string) {
    const bus = new FakeBus();
    const cb1: BusCallback = createFunctionSpy();

    const w = new BusWrapper(bus);
    bus.subscribe(ch1, cb1);
    bus.startCallback();

    await wait(1 + 3);

    Expect(cb1).toHaveBeenCalled().exactly(1);
    Expect(cb1).toHaveBeenCalledWith(ch1, msg1);
}
```

**Comment by wip0** [comment]
Amm, I confirm that it is a vscode insider bug whereas vscode 1.19.2 is working fine.
sorry for any inconvenience caused.

Please close this issue.

**Comment by wip0** [comment]
Amm, it is my fault. If I debug the test code, it will take a long time for debugging then timeout event is trigger.

So I have to increase the value to be something as below
```
@Timeout(100000)
```

sorry for any inconvenience caused.
Please close this issue.
