### ISSUE TITLE
Replace getters only by readonly properties 

### ISSUE THREAD

**Issue by jhm-ciberman** [alsatian-test/alsatian#452]
Hello. I've seen this pattern often in the codebase:
```typescript
export class Foo {
  protected _bar: string;
  public get bar(): string{
    return this._bar;
  }

  public constructor(bar: string) {
    this._bar = bar;
  }
}
```

I think that this can be replaced by:

```typescript
export class Foo {
  protected readonly bar: string;
  public constructor(bar: string) {
    this.bar= bar;
  }
}
```

This makes the code more readable, mantainable, documentable and froze the property to be modified outside the constructor.

**Comment by Jameskmonger** [comment]
I'm in favour of this

**Comment by jhm-ciberman** [comment]
@jamesrichford

**Comment by jamesrichford** [comment]
Yep, no objections. Sounds great :)

**Comment by jhm-ciberman** [comment]
Fine. I will refactor that in https://github.com/alsatian-test/alsatian/pull/451
