### ISSUE TITLE
toEqual returns false if you explicitly set a property to undefined

### ISSUE THREAD

**Issue by hisuwh** [alsatian-test/alsatian#456]
I was doing something like this:
```ts
const myObject = {
  foo: "test",
  bar: {
     foobar: "test"
  }
};

const buzz = myObject.buzz !== undefined
  ? { ...myObject.buzz, fizz: "test" }
  : undefined;

const result = { ...myObject, buzz };

Expect(result).toEqual(myObject); // returns false
```

I can understand why these are not equal but the issue is the way alsatian reports them suggests they are equal:
```
Expected { foo: "test", bar: { foobar: "test" } } to be equal to { foo: "test", bar: { foobar: "test" } }.
```

**Comment by jamesrichford** [comment]
The erroneous reporting is due to `JSON.stringify` as that is picking out the undefined properties. Looks like we'll need to rework how we strongly :)

**Comment by hisuwh** [comment]
@jamesadarich what is happening with this.  You closed Davids proposed fix as you have said this is fixed with 3.0.0 but I'm still seeing this issue

**Comment by hisuwh** [comment]
ok I take it back. Testing a bit further I can see the undefined thing in the output.  My problem must be different.  I'm getting an object back and comparing it to a seemingly identical object but getting a match error

**Comment by jamesadarich** [comment]
@hisuwh do you think there's an issue here? implicit `undefined` and explicit `undefined` are different things as long as it's displaying I think this is fine and can be closed unless I'm missing something?

**Comment by hisuwh** [comment]
I think this issue can be closed.  My issue was weird and I haven't totally got the bottom of it.

```ts
const resultObject = someMethodThatReturnsObject();

const expectedObject = { 
   // object with exact properties and values of resultObject
};

Expect(resultObject).toEqual(resultObject); // pass
Expect(resultObject).toEqual(expectedObject); // fail
Expect(resultObject).toEqual({ ...resultObject }); // fail
```

I ended up working around this by doing:
```ts
Expect(JSON.stringify(resultObject)).toEqual(JSON.stringify(expectedObject));
```

**Comment by jamesadarich** [comment]
I think likely this is an implicit / explicit undefined issue. I'm going to close this but show me the code and can confirm.

Would be interesting to see if this is the case we may want to get better output for it.
