### ISSUE TITLE
Improve call stack issue solution

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#46]
Currently using setTimeout on fixture change to help out with avoiding a huge call stack, need to neaten up the code for a nicer solution

**Comment by Jameskmonger** [comment]
Not sure there are any other solutions @jamesrichford...

**Comment by Jameskmonger** [comment]
@jamesrichford https://github.com/sindresorhus/clean-stack

**Comment by Jameskmonger** [comment]
Resolved by #130
