### ISSUE TITLE
Allow Map's to be expected to be Empty

### ISSUE THREAD

**Issue by graywolf336** [alsatian-test/alsatian#462]
First off, thanks for this amazing project! I am enjoying working with it.

Currently I have one request - `toBeEmpty` can only be used with arrays, strings, and object literals. However, I would like to see the `Map` be added since it has the property `size` that returns the amount of records in the map.

**Comment by jamesadarich** [comment]
Sounds like a great recommendation! We'd certainly accept a pr for this :)

**Comment by graywolf336** [comment]
Hehe the open source response, I love it 😍 I'll look into adding it next week, should no one have done it yet. :)
