### ISSUE TITLE
toEqual does not work correctly with Buffer

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#465]
`toEqual` for `Buffer` instances should use `bufferA.equals(bufferB) === true`

At the moment, it does not check correctly:

```
const bufA = Buffer.alloc(4);
bufA.writeUInt8(0x12, 0);
bufA.writeUInt8(0x34, 1);

const bufB = Buffer.from([ 0x12, 0x34 ]);

Expect(bufA).toEqual(bufB);
```

It fails because `bufA` is actually `[ 0x12, 0x34, 0x00, 0x00 ]` - but `Buffer.equals` ignores that

**Comment by jamesadarich** [comment]
I think this makes sense to be a separate function. As I would say that for an array `[ 1, 2, ]` is not equal to `[ 1, 2 ]` (note the first has 3 items). I think equality should be identical without being the same instance, in these cases the lengths are not the same where as the contents are. For example

```typescript
Expect(buffer).toHaveEqualContentsTo(exampleBuffer);
```

**Comment by Jameskmonger** [comment]
@jamesadarich My first post was actually two issues.

1. `toEqual` does not call `Buffer.equals` when it probably should - this will match for `[ 1, 2 ]`-`[ 1, 2 ]` but not for `[ 3, 4 ]`-`[ 3, 4,  ]`
2. There is no way to check and ignore empty trailing contents - e.g. in your example above.

I think we should change `toEqual` and add `toHaveEqualContentsTo` also.

**Comment by pathurs** [comment]
So I'm not seeing how you can declare a `Buffer` by using `[ 1, 2, ]`.

Test code:

```
const buf1 = Buffer.from([1,2]);
const buf2 = Buffer.from([1,2,]);

console.log(buf1);
console.log(buf2);
console.log(buf1.length);
console.log(buf2.length);
console.log(buf1 == buf2);
console.log(buf1 === buf2);
console.log(buf1.equals(buf2));
console.log(buf1.compare(buf2));
console.log(buf1.toString() == buf2.toString());
console.log(buf1.toString() === buf2.toString());
```

Results:
```
<Buffer 01 02>
<Buffer 01 02>
2
2
false
false
true
0
true
true
```

**Comment by Jameskmonger** [comment]
@pathurs notice there that `buf1.equals(buf2)` is true, while `buf1 == buf2` and `buf1 === buf2` are both false.

**Comment by pathurs** [comment]
This also returns false:

`Buffer.from([1, 2]) == Buffer.from([1, 2]);`

**Comment by pathurs** [comment]
Hi @Jameskmonger, I attempted to find a solution that would match your expectations, while allowing `BufferLike` types to match as well.
