### ISSUE TITLE
ts-node included twice in Alsatian package.json

### ISSUE THREAD

**Issue by pathurs** [alsatian-test/alsatian#469]
https://github.com/alsatian-test/alsatian/blob/f9d7970ea5fd47ef81f64a4b5cab0e0ed7feb7da/package.json#L108-L109

Perhaps this was meant to be `^3.3.0 || ^4.0.0`?

**Comment by jamesadarich** [comment]
Awesome, thanks for the PRs :) Glad you're enjoying using it. It'd be wonderful if you could help out. Are there any particular that interest you?

**Comment by pathurs** [comment]
@jamesadarich flick me an email at pathurs123@gmail.com, better to discuss there. :)
