### ISSUE TITLE
Rework Expect

### ISSUE THREAD

**Issue by jamesadarich** [alsatian-test/alsatian#473]
Currently matchers are checking types in them where as ideally we could override and overload to rework this (hopefully)

**Comment by jamesadarich** [comment]
Matchers that need to, remove custom error and replace with custom details;

- [ ] toBe
- [ ] toEqual
- [ ] toMatch
- [ ] toBeDefined
- [ ] toBeNull
- [ ] toBeTruthy
- [ ] toContain
- [ ] toBeEmpty
- [ ] toBeGreaterThan
- [ ] toBeLessThan
- [ ] toThrow
- [ ] toThrowAsync
- [ ] toThrowError
- [ ] toThrowErrorAsync
- [ ] toHaveBeenCalled
- [ ] toHaveBeenCalledWith
- [ ] toHaveBeenSet
- [ ] toHaveBeenSetTo

**Comment by jamesadarich** [comment]
@hisuwh @OwenPattison @woahitsjc I've assigned you guys some stuff as promised 👍 

What needs to be done is for the assigned matchers (above) if we could:

1. validate the use of `_registerMatcher` I'm not so convinced about this pattern. Would value some input :)
2. ensure that the message and extras are correct for that context as you'll be able to see in the output that the extras are what is displayed instead of expected and actual values to give the user more context (e.g. a diff for `toEqual`)
3. if relevant refactoring / creating overloads in other type matchers where relevant - e.g. if the behaviour should be different for objects than anything else we should write an overload

Any questions let me know and thanks you top peeps :)

**Comment by hisuwh** [comment]
Do we need to base this off release/3.0.0

**Comment by jamesadarich** [comment]
@hisuwh yep,

@Jameskmonger as above

**Comment by jamesadarich** [comment]
@georgyfarniev - this issue is the key issue that's blocking 3.0.0 if you wouldn't mind checking out the comment above and applying that for `toBeGreaterThan` and `toBeLessThan` that'd be awesome. Any questions please let me know :)

**Comment by georgyfarniev** [comment]
@jamesadarich I think I need more details about this task. It's not clear for me about overloading part, as long as overloading in ts are different from other languages. Also, what is **_registerMatcher**? And which branch is currently primary for development? master?

**Comment by jamesadarich** [comment]
* overloads aren't relevant for your piece as you'll only be working with `number`s so no need to worry
* `_registerMatcher` is a function on the `Matcher` base class that manages failure recording and the output to the console. You pass whether it passed as a boolean, a message to be displayed, the expected result and an object of items you want to be displayed to the user when a test fails.
* release/3.0.0 is the branch being used for the new work at the moment

**Comment by jamesadarich** [comment]
Done
