### ISSUE TITLE
Is safe to migrate to Alsatian 3.0.0 alpha?

### ISSUE THREAD

**Issue by jhm-ciberman** [alsatian-test/alsatian#514]
Hello. I have a project (https://github.com/jhm-ciberman/docs_gm) which uses Alsatian 2. It is safe to migrate to Alsatian 3 alpha? Or do I need to wait to a stable release? 

Thanks.

**Comment by jamesadarich** [comment]
The current state of the alpha is currently building up the new APIs and behaviours. The design has now been fixed but not fully implemented so there may be missing functionality / slightly strange behaviour in some cases.

Basically it's in preview and shouldn't be relied on at the moment. The plan is:

alpha - early preview (still building functionality)
beta - early adoption (bug fixes and non breaking changes only)
rc - ready for general adoption (bug fixes only)

Hoping to get to beta asap but any help would be much appreciated :)

**Comment by jamesadarich** [comment]
@jhm-ciberman beta is now out, I'd say you should be safe to migrate now - I'm fixing any bugs as priority but just tidying up the repo/CI etc. then will be ready for main release.
