### ISSUE TITLE
Alsatian printing "plete plete plete" when running in CI mode

### ISSUE THREAD

**Issue by jhm-ciberman** [alsatian-test/alsatian#549]
When alsatian runs in CI mode (Travis), it prints the word "plete". I don't know what it means.

Example: https://travis-ci.org/jhm-ciberman/docs_gm/jobs/570427708#L242 (Line 242 onwards)

**Comment by jhm-ciberman** [comment]
I realized that it can be the word "complete". But still don't think this is considered a feature. Haha.

**Comment by jamesadarich** [comment]
Haha yes this is frustrating. It's to do with how the CLI output differs in these CI environments where out tries to overwrite previous updates.

You can pass the `--hide-progress` option and this will remove these messages.

**Comment by jhm-ciberman** [comment]
I think my building and testing workflow it's a little too complicated at the moment. Do you have any suggestion to remove the progress when `npm test` is executed in TravisCI but preserve it when I execute `npm test` from my local environment? 

```json
  "scripts": {
    "test": "npm run lint && npm run coverage",
    "test-only": "npm run build && npm run unit-tests",
    "unit-tests": "alsatian \"./dist/tests/unit/**/*.spec.js\"",
    "build": "tsc -p .",
    "watch": "tsc -p . --watch",
    "clean": "rimraf ./dist/ ./coverage/ ./.nyc_output/",
    "coverage": "npm run build && nyc npm run unit-tests",
    "report-coverage": "nyc report --reporter=text-lcov | coveralls",
    "lint": "tslint --project . -t verbose",
    "prepublishOnly": "npm run clean && npm run build",
    "integration": "npm run build && npm link && alsatian \"./dist/tests/integration/**/*.spec.js\""
  },
```

**Comment by jamesadarich** [comment]
Looking at your steps you can remove the build step and pass the .ts files in directly. Maybe the best option to resolve this is to set this option to true if the `CI` environment variable is set to `true` as looks like Travis and Circle CI both do this and it's a sensible default. Fancy giving this a go? :)

**Comment by jhm-ciberman** [comment]
I have tried changing passing the ts files directly and it gives me an error:

```
> docs_gm@4.1.0 unit-tests C:\repos\docs_gm\docs_gm-core
> alsatian "./tests/unit/**/*.spec.ts"

ERROR LOADING FILE: C:/repos/docs_gm/docs_gm-core/tests/unit/cli/Cli.spec.ts
Error: Cannot find module '../../../package.json'
Require stack:
- C:\repos\docs_gm\docs_gm-core\src\cli\Cli.ts
- C:\repos\docs_gm\docs_gm-core\tests\unit\cli\Cli.spec.ts
- C:\repos\docs_gm\docs_gm-core\node_modules\alsatian\dist\core\file-requirer.js
- C:\repos\docs_gm\docs_gm-core\node_modules\alsatian\dist\core\index.js
- C:\repos\docs_gm\docs_gm-core\node_modules\alsatian\dist\core\alsatian-core.js
- C:\repos\docs_gm\docs_gm-core\node_modules\alsatian\dist\cli\cli-test-runner.js
- C:\repos\docs_gm\docs_gm-core\node_modules\alsatian\dist\cli\alsatian-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\repos\docs_gm\docs_gm-core\src\cli\Cli.ts:12:21)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Module.replacementCompile (C:\repos\docs_gm\docs_gm-core\node_modules\nyc\node_modules\append-transform\index.js:58:13)
    at Module.m._compile (C:\repos\docs_gm\docs_gm-core\node_modules\ts-node\src\index.ts:473:23)
    at module.exports (C:\repos\docs_gm\docs_gm-core\node_modules\nyc\node_modules\default-require-extensions\js.js:7:9)
    at C:\repos\docs_gm\docs_gm-core\node_modules\nyc\node_modules\append-transform\index.js:62:4npm ERR! code ELIFECYCLE
```

The line that gives me the problem is where I load the package.json to autodetermine the package number and show it to the user (So, i don't have to manually update the number each time)

```
// File is: ./src/cli/Cli.ts
const packageJSON = require("../../../package.json");
```

The require uses 3 `..` because when you run `tsc -p .` the output is normally in the `./dist` folder. Any sugestion? 
Repo: https://github.com/jhm-ciberman/docs_gm

**Comment by jamesadarich** [comment]
You need to set `resolveJsonModule` to `true` in the `compilerOptions` of your `tsconfig.json`

**Comment by jamesadarich** [comment]
Sorry misread the problem I think instead if you set `rootDir` to `./src` that should omit this from the `dist` folder keeping the relative root at the same level.

Full disclosure I'm not near a computer so can't test. Let me know if this is helpful :)

**Comment by jhm-ciberman** [comment]
I refactored a lot my repo and now it works like a charm. The problem is that is super ugly to have to use the --hide-progress flag externally when running in CI mode. 

I've made this tiny PR. Can you check it? https://github.com/alsatian-test/alsatian/pull/552

**Comment by jamesadarich** [comment]
This has now been published, are you happy with the resolution? :)

**Comment by jhm-ciberman** [comment]
I've just updated Alsatian to the latest version and now it works perfect! Thanks!

**Comment by jamesadarich** [comment]
Perfect! :)
