### ISSUE TITLE
Consider different output formats

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#55]
Currently alsatian only outputs tap. This is great and should be an option but probably want a funkier more human friendly default output along with possibly different outputs for parallel vs serial and even a performance focused one for those mega legends writing millions of tests

**Comment by jamesrichford** [comment]
@Jameskmonger  - thoughts?

**Comment by Jameskmonger** [comment]
@jamesrichford Not sure there's much of a need to give other formats. The point of TAP is that it allows people to choose the reporter that they like with confidence. There are plenty of human-readable TAP reporters such as [tap-prettify](https://github.com/toolness/tap-prettify) or [faucet](https://github.com/substack/faucet).

**Comment by jamesrichford** [comment]
Yeah, I guess my thoughts were the lack of a standard for the TAP output in terms of reading diffs etc. and that it looks a bit neater out of the box were potential drivers for this one

**Comment by jamesrichford** [comment]
Cool as discussed we'll create our own reporter to do this, I'll make a repo :)
