### ISSUE TITLE
Feature idea: export a simple function that runs alsatian on the provided file path

### ISSUE THREAD

**Issue by gobengo** [alsatian-test/alsatian#555]
Issue created because @jamesadarich [asked](https://github.com/alsatian-test/alsatian/pull/502#issuecomment-525939323).

After I published the following:

btw, with Alsatian I almost always use copy paste this pattern into my project. I should make it a lib or something, but you may also want to incorporate it as a helper into the core/official packages.

I want to be able to execute my test files one-by-one to run the tests in there, just like any other normal unix script: `./SomeTest.test.ts`. 

This is nice for a number of reasons, including I can easily use a node debugger in the tests I'm writing by hitting 'F5' in vscode to execute the current file.

In my test files I do:
```
import "../path-to/alsatian-cli"
if (require.main === module) {
  (async () {
    await cli(__filename);
  })();
}
```

src/test/alsatian-cli.ts
```
import { TestOutputStream, TestRunner, TestSet } from "alsatian";
import { join } from "path";
import { TapBark } from "tap-bark";

type TestCLI = (filesOrGlobs: string | string[]) => Promise<void>;

/**
 * Test CLI
 * If passed a filename, will run test in that file.
 * Otherwise, run tests in all files.
 */
export const cli: TestCLI = async (
  filesOrGlobs: string | string[],
): Promise<void> => {
  process.on("unhandledRejection", error => {
    console.error(error);
    throw error;
  });
  await main(filesOrGlobs);
};

/**
 * Run all tests
 */
async function main(filesOrGlobs: string | string[]): Promise<void> {
  // Setup the alsatian test runner
  const testRunner: TestRunner = new TestRunner();
  const tapStream: TestOutputStream = testRunner.outputStream;
  const testSet: TestSet = TestSet.create();
  testSet.addTestsFromFiles(filesOrGlobs);

  // This will output a human readable report to the console.
  const bark = TapBark.create();
  const barkTransform = bark.getPipeable();
  tapStream.pipe(barkTransform).pipe(process.stdout);

  // Runs the tests
  const timeout = process.env.TEST_TIMEOUT_MS
    ? parseInt(process.env.TEST_TIMEOUT_MS, 10)
    : 60 * 1000;
  await testRunner.run(testSet, timeout);
}
```

@jamesadarich then asked:

> Is the goal here to ensure that tests run sequentially? Because that should already be happening.

My response:

No, my goals are twofold:
* Be able to run the tests in a file by just passing it to `ts-node`. Or it's output js to `node`. Or using default IDE features for 'run this file' like pressing F5 in VS Code
* Similarly, be able to run the tests without having to go through the `alsatian` bin script / cli. One of the reasons I really like alsatian is it doesn't require any magic globals like jasmine/jest. I similarly want to not be tied to having to run the file with a special cli. I like my tests to be 'just typescript scripts'. The [nodejs core testing guide](https://github.com/nodejs/node/blob/master/doc/guides/writing-tests.md#what-is-a-test) has a good philosophy on this: tests are just scripts that exit 1 or 0.

I published a thing here since I've copypastad this into a handful of different projects now and I want to depend on it. But I'd much rather just import something equivalent from the `alsatian` library itself. If you're not into it, though, no sweat.

https://github.com/gobengo/alsatian-cli-function

**Comment by jamesadarich** [comment]
Thanks for this, just so I can clarify the goal here. Looks like you're looking to run a test you are currently writing from the scope of the IDE, is that correct?

If so are we potentially looking at an end goal of some sort of extension?

**Comment by jamesadarich** [comment]
Closing this one now as the extension handles this and all other use cases can still use the CLI  `alsatian ./path/to/specific.spec.ts` or implement similarly to how the extension does.
