### ISSUE TITLE
Typo `depreacated` => `deprecated`

### ISSUE THREAD

**Issue by mikkelbu** [alsatian-test/alsatian#557]
This is a very minor issue. We are using several of the decorators mentioned in #505 and the typo in the word "depreacated" always stands out when I read our logs.

I'll be most happy to contribute a PR to solve this minor issue.

**Comment by jamesadarich** [comment]
Good find, a PR would be galt l gladly received :)

**Comment by jamesadarich** [comment]
Published with 3.1.0 let me know if all is working good from your end :)

**Comment by mikkelbu** [comment]
@jamesadarich It works here - and I forgot to mention this issue in #558 - so this issue has not been closed. I'll close it now and thanks for your work on Alsatian.

**Comment by jamesadarich** [comment]
Thanks for the contribution @mikkelbu
