### ISSUE TITLE
@Mock and @InjectMocks decorator

### ISSUE THREAD

**Issue by Gr33nbl00d** [alsatian-test/alsatian#560]
A nice feature would be ts-mockito support 
https://github.com/NagRock/ts-mockito

so i could do the following:

@TestFixture()
export class MyTest {
  @Mock
   private myMock:MockClass;
   @InjectMocks(new MyClass())
    private sut: MyClass;
}

Alsatian would then create a mock and inject it in the MyClass instance.

**Comment by Gr33nbl00d** [comment]
I added this myself with a new npm package:

https://github.com/Gr33nbl00d/alsatian-tsmockito

**Comment by jamesadarich** [comment]
Nice work, I'll add a link in the docs for this :)

**Comment by Gr33nbl00d** [comment]
Thank you :) Cool :)
