### ISSUE TITLE
Alsatian Test Coverage with NYC can not get test result

### ISSUE THREAD

**Issue by acgotaku** [alsatian-test/alsatian#611]
This is my demo: https://github.com/acgotaku/alsatian-codecov

Run `yarn check-coverage`, output:

```
> alsatian src/**/*.spec.ts

  Pass: 3 / 3
  Fail: 0 / 3
  Ignore: 0 / 3
  
  
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|

```
NYC can not output correct test result.
Could you help me find the problems from my demo?

Thanks very much!

**Comment by jamesadarich** [comment]
I'll have a peek and update you when I find something :)

**Comment by jamesadarich** [comment]
Hey @acgotaku,

I've submitted Pull Request -> https://github.com/acgotaku/alsatian-codecov/pull/1 that resolves this simply, it's just the nyc config that's incorrect.

The `nyc` property you had in the below config is not needed and only required if your config is in the `package.json`

Current

```json
{
  "nyc": {
    "extends": "@istanbuljs/nyc-config-typescript",
    "all": true,
    "check-coverage": true
  }
}
```

Corrected

```json
{
  "extends": "@istanbuljs/nyc-config-typescript",
  "all": true,
  "check-coverage": true
}
```

**Comment by acgotaku** [comment]
Hello @jamesadarich Thank you very much!

Change the config file fix my problem!

**Comment by acgotaku** [comment]
@jamesadarich Maybe you can update the document. https://github.com/alsatian-test/alsatian/wiki/Check-Test-Coverage-with-NYC

Let user add test coverage more easy!
