### ISSUE TITLE
New line will look nicely.

### ISSUE THREAD

**Issue by leejinseok** [alsatian-test/alsatian#613]
This tool is very nice. But below is ugly. 
I suggest insert new line. thanks you for nice testing tool.
![image](https://user-images.githubusercontent.com/7136340/69495517-17687500-0f0b-11ea-81cf-99df949b488e.png)

**Comment by jamesadarich** [comment]
Haha yes, definitely - a fix has been published.

Thanks for raising. Any other issues please feel free to let us know :)
