### ISSUE TITLE
NPM Distribution references js.map and ts files that are excluded

### ISSUE THREAD

**Issue by jamesrichford** [alsatian-test/alsatian#62]
We need to either recompile without mapping or distribute the ts and maps. Thoughts @Jameskmonger ?

**Comment by Jameskmonger** [comment]
I think we should only distribute the JS on npm @jamesrichford.. in my opinion npm should be runtime-only.

**Comment by jamesrichford** [comment]
After further thought I think distributing maps and TS makes sense. If a user doesn't debug through to alsatian code then they don't lose anything but if they do then they'll get a lot more insight and clarity.

The only downside is distribution size which is a negligible increase considering this will only be used in dev
