### ISSUE TITLE
No such file or directory on cli

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#77]
When running `alsatian` from the command line in Ubuntu, I get:

    : No such file or directory

This doesn't occur with gulp.

**Comment by jamesrichford** [comment]
Ace @jameskmonger, good to have this confirmed. Strange though because after we found this I put an integration test in that passes on Travis Linux and OSX.

Any ideas?

**Comment by Jameskmonger** [comment]
Okay @jamesrichford, I've just cloned the latest copy of this repo and published it to npm under the name `jkmalsatian`, and that works fine. Looks like maybe the publish just got a bit borked up - probably just publish it again?

**Comment by jamesrichford** [comment]
Which version did you have installed? Alpha.6?

**Comment by jamesrichford** [comment]
@Jameskmonger  just published alpha.7 - let me know if this works :)

**Comment by Jameskmonger** [comment]
Odd. It doesn't look like this works. It seems like something that happens when it's published on your PC is causing it to break...

**Comment by jamesrichford** [comment]
Hmmm... I take it that it's the file in the bin folder that's missing? Maybe it's a problem with my checkout of the repo? 

I'll have to figure out about republishing, also need to figure out what's causing the problem so can add a script to prevent this issue in future.

I guess first step is to compare your npm package to mine! :)

**Comment by jamesrichford** [comment]
Thinking maybe this is the problem!

https://github.com/npm/npm/issues/12371

I'm going to change my git settings and try publishing alpha.8. Then if this solves it probably add a prepublilsh script to ensure line endings are set correctly.

**Comment by jamesrichford** [comment]
Right @Jameskmonger - so I've got a potential fix in npm as alpha.8 so hopefully this resolves it - I've ensured that TypeScript compiles js with LF line endings :)

**Comment by Jameskmonger** [comment]
That's sorted it @jamesrichford - exactly what they said over at [nodejs](https://github.com/nodejs/node/issues/8093#issuecomment-239606784)!

**Comment by jamesrichford** [comment]
Nice one! Cheers for your help on this one mate!

**Comment by Jameskmonger** [comment]
No worries @jamesrichford thanks for fixing it! I didn't notice any `tsconfig` changes for it (did you forget to push? or was it local system settings)
