### ISSUE TITLE
Disable buildOnSave

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#92]
`buildOnSave` and `compileOnSave` seem to crash my Atom repeatedly. Turning them off solves it (still gives me compilation warnings in the code though :smile:)

**Comment by jamesrichford** [comment]
Is this on your home computer? Does intellisense still update itself nicely?

**Comment by Jameskmonger** [comment]
Nope on the work PC @jamesrichford so I don't think it's a performance issue. Intellisense seems to still work.

The only other option for me to work in Atom is to disable `atom-typescript` which then makes me lose syntax highlighting.
