### ISSUE TITLE
IgnoreTests annotation has no effect

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#98]
The `@IgnoreTests` annotation does not have any effect on whether a test fixture is executed or not.

**Comment by jamesrichford** [comment]
Make sure you implement ignore reason in this too

**Comment by Jameskmonger** [comment]
@jamesrichford I'd like to talk to you tomorrow about how we can solve this if possible.

At the moment it doesn't look like we can get any information about the fixture that a test is in neatly, which means that cascading down the ignore reason is going to be tricky.

**Comment by jamesrichford** [comment]
Closed via #110
