### ISSUE TITLE
Log fixture info to output

### ISSUE THREAD

**Issue by Jameskmonger** [alsatian-test/alsatian#99]
I think it would be good to log the fixture info to the output. Like this:

```
# FIXTURE EmitResultTests
ok 1 shouldEmitWithCorrectTestId [ 1 ]
ok 2 shouldEmitWithCorrectTestId [ 2 ]
ok 3 shouldEmitWithCorrectTestId [ 3 ]
ok 4 shouldEmitWithCorrectTestDescription # skip test descriptions are not implemented for now
# FIXTURE EmitVersionTests
ok 5 shouldEmitVersion13
```

At present there is no way to log any info about the fixture, which means that the reason given in the `IgnoreTests` attribute will not be logged

**Comment by Jameskmonger** [comment]
Which milestone are you thinking @jamesrichford?

**Comment by jamesrichford** [comment]
alpha.10, it's a neat simple feature I think so might as well get it in sooner

**Comment by jamesrichford** [comment]
Probably implementation would be ```@TestFixture``` decorator similar to ```@Test```?

**Comment by Jameskmonger** [comment]
Not sure we need a decorator for it @jamesrichford

**Comment by jamesrichford** [comment]
If you want to give it a name other than the fixture name e.g. with spaces or special characters

**Comment by Jameskmonger** [comment]
Hmm yes good point. I think maybe they should be separate features though so that we can get this one through faster :stuck_out_tongue_closed_eyes:
